name: Zip Release
  # You may pin to the exact commit or the version.
  # uses: TheDoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d
  uses: TheDoctor0/zip-release@0.6.0
  with:
    # Filename for archive
    filename: # default is release.zip
    # Base path for archive files
    path: # optional, default is .
    # Working directory before zipping
    directory: # optional, default is .
    # List of excluded files / directories
    exclusions: # optional, default is 
    # Tool to use for archiving
    type: # optional, default is zip
