name: Zip Release
  uses: TheDoctor0/zip-release@0.6.0
  with:
    # Filename for archive
    filename: # default is release.zip
    # Base path for archive files
    path: # optional, default is .
    # Working directory before zipping
    directory: # optional, default is .
    # List of excluded files / directories
    exclusions: # optional, default is 
    # Tool to use for archiving
    type: # optional, default is zip
